---
permalink: install/concept_using_lun_groups_to_partition_the_load_over_v_series_connections.html 
sidebar: sidebar 
keywords: benefits, use, multiple, lun, groups 
summary: Puede usar varios grupos de LUN en su configuración de almacenamiento para aumentar la capacidad y para mejorar el rendimiento del sistema distribuyendo la carga de trabajo por más puertos objetivo. 
---
= Ventajas de usar varios grupos de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar varios grupos de LUN en su configuración de almacenamiento para aumentar la capacidad y para mejorar el rendimiento del sistema distribuyendo la carga de trabajo por más puertos objetivo.

Un _lun group_ es un conjunto de dispositivos lógicos de la cabina de almacenamiento a los que accede un sistema ONTAP a través de las mismas rutas. El administrador de la cabina de almacenamiento configura un conjunto de dispositivos lógicos como grupo para definir qué WWPN de host pueden acceder a ellos. ONTAP se refiere a este conjunto de dispositivos como _lun group_.

Los beneficios de usar varios grupos de LUN son los siguientes:

* Hay límites sobre el número de LUN que puede admitir un par de puertos de iniciador de FC determinado.
+
En el caso de cabinas de almacenamiento grandes en particular, la capacidad necesaria puede superar lo que puede proporcionar un solo grupo de LUN. Por lo tanto, el uso de varios grupos de LUN puede ser beneficioso.

* Se puede particionar la carga de los LUN de cabina a través de los pares de puertos iniciadores FC.


[NOTE]
====
No se admite el uso de varios grupos de LUN en todas las cabinas de almacenamiento. Consulte _Matriz de interoperabilidad_ para determinar si la cabina de almacenamiento admite una configuración que utilice varios grupos de LUN.

====
*Información relacionada*

https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"]
