---
permalink: install/concept_considering_checksum_type_when_planning_array_lun_size_and_number.html 
sidebar: sidebar 
keywords: consider, checksum, type, plan, array, lun, size, number 
summary: Cuando planifique la cantidad y el tamaño de LUN de cabina que necesita para ONTAP, debe tener en cuenta el impacto del tipo de suma de comprobación en la cantidad de espacio utilizable en el LUN de cabina. Se debe especificar un tipo de suma de comprobación para cada LUN de cabina asignado a un sistema ONTAP. 
---
= Considerando el tipo de suma de comprobación al planificar el tamaño y el número de LUN de cabina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando planifique la cantidad y el tamaño de LUN de cabina que necesita para ONTAP, debe tener en cuenta el impacto del tipo de suma de comprobación en la cantidad de espacio utilizable en el LUN de cabina. Se debe especificar un tipo de suma de comprobación para cada LUN de cabina asignado a un sistema ONTAP.

Cuando un sistema ONTAP asigna un LUN de cabina en la cabina de almacenamiento para que lo utilice , ONTAP considera el LUN de cabina como un disco sin formato y sin formato. Cuando se asigna un LUN de cabina a un sistema ONTAP, se especifica el tipo de suma de comprobación, lo que le indica a ONTAP cómo formatear el LUN de cabina sin configurar. El impacto del tipo de suma de comprobación en el espacio utilizable depende del tipo de suma de comprobación especificado para la LUN.
