---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: Cuando los errores de almacenamiento muestran indicadores de una condición de error, debe determinar por qué se produjo el error y cómo solucionarlo. 
---
= Los errores de almacenamiento muestran mensajes y su resolución
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando `storage errors show` marca una condición de error, debe determinar por qué se produjo el error y cómo solucionarlo.

En la siguiente tabla, se enumeran los errores de configuración del entorno de administración detectados por `storage errors show` y se le remite a información detallada sobre las causas de cada error y su resolución.

|===
| `storage errors show` mensaje | Para obtener más información sobre este mensaje, consulte... 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``.
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[Todas las rutas a un LUN de cabina se encuentran en la misma controladora de cabina de almacenamiento]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`.
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[ID de LUN duplicados en un puerto de destino]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``.
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[Se presentó la LUN de control de acceso]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`.
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[Los LUN de cabina se configuran con modos de conmutación por error contradictorios]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`.
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Menos de dos rutas a un LUN de cabina]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[El LUN de la cabina es demasiado pequeño o demasiado grande]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[El LUN de la cabina es demasiado pequeño o demasiado grande]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`.
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[Los ID de LUN para el mismo LDEV no coinciden]

El direccionamiento del conjunto de volúmenes es inconsistente



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`.
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[El LUN de la cabina se marca como externo y tiene una reserva]

|===