---
permalink: install/reference_reasons_for_more_paths_to_an_array_lun_than_expected.html 
sidebar: sidebar 
keywords: reasons, paths, array, lun, expected, output, show, config, issue 
summary: Las razones principales de una ruta adicional inesperada a un LUN de cabina son problemas de división en zonas y demasiados cables. Tres rutas a un LUN de cabina no es una práctica recomendada, pero no es necesario que solucione este problema. 
---
= Razones de más rutas a un LUN de cabina de lo esperado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las razones principales de una ruta adicional inesperada a un LUN de cabina son problemas de división en zonas y demasiados cables. Tres rutas a un LUN de cabina no es una práctica recomendada, pero no es necesario que solucione este problema.



== Ejemplo de resultado de show de configuración de la cabina de almacenamiento

El par de puertos iniciadores de FC del sistema ONTAP es 0A y 0C. El siguiente ejemplo muestra una ruta adicional, 0b, en la `storage array config show` salida:

[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count   Array Name       Array Target Port   Initiator
----------   ----- -----  ----------------  ------------------  ----------
mysystem1a    1     3     HITACHI_DF600F_1  50060e80004291c0    0a
                                            50060e80004291c1    0b
                                                                0c

3 entries were displayed.
----
[NOTE]
====
Si un iniciador de la `storage array config show` salida no está precedido por un puerto de destino de la cabina, el iniciador se conecta al mismo puerto de destino de la cabina que el iniciador encima de él.

====


== Explicación

Tres rutas dentro de un grupo de LUN indican que hay una ruta adicional. En las configuraciones de ONTAP, la práctica recomendada es dos o cuatro rutas.

Las razones por las que podría haber más rutas de las esperadas incluyen las siguientes:

* Se conectaron más cables de los necesarios.
* Un error de configuración de división en zonas ha provocado una ruta adicional.




== Resolver el problema

Tener una ruta adicional no es una práctica recomendada, pero no es incorrecta desde el punto de vista del sistema. No tiene que solucionar este problema. Si desea solucionar el problema para alinearlo con la configuración deseada, realice los siguientes pasos:

. Compruebe el cableado y la configuración de la división en zonas para la causa y, a continuación, corrija el problema que está causando la ruta adicional.
. Una vez solucionado el problema, ejecute `storage array config show` de nuevo para confirmar que la ruta adicional ha desaparecido.

